apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-downloader
  labels:
    app: yt-downloader
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-downloader
  template:
    metadata:
      labels:
        app: yt-downloader
    spec:
      containers:
      - name: yt-downloader
        image: ytdlregistry.azurecr.io/ytdlimages:30
        env:
        - name: azConnectionString
          valueFrom:
            secretKeyRef:
              name: az-conn
              key: azConnectionString
        ports:
        - containerPort: 5002
