apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdl
  labels:
    app: ytdl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytdl
  template:
    metadata:
      labels:
        app: ytdl
    spec:
      containers:
        - name: yt-downloader
          image: ytdlregistry.azurecr.io/ytdlimages:25
          env:
        - name: az-conn
          valueFrom:
            secretKeyRef:
              name: az-conn
              key: AZURE_CONNECTION_STRING
          ports:
            - containerPort: 5002
