apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytdl
  labels:
    app: ytdl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytdl
  template:
    metadata:
      labels:
        app: ytdl
    spec:
      containers:
        - name: ytdl
          image: ytdlregistry.azurecr.io/ytdlimages:13
          ports:
            - containerPort: 5002
