apiVersion: v1
kind: Service
metadata:
  name: yt-downloader
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: yt-downloader
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
