name: ytdl
on:
  push:
    branches:
      - main
    #paths:
    #  - 'manifests/**'
  workflow_dispatch: {}
env:
  ACR_RESOURCE_GROUP: demosResourceGroup
  AZURE_CONTAINER_REGISTRY: ytdlregistry
  CLUSTER_NAME: bvzfitDemoAKSCluster
  CLUSTER_RESOURCE_GROUP: demosResourceGroup
  CONTAINER_NAME: ytdlimages
  
jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/login@v2.1.0
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to ACR
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.REPOPASS }}
      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.run_number }}

  runScript:
    needs: buildImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          chmod +x ./updatek8s.sh
          ./updatek8s.sh $GITHUB_RUN_NUMBER
